kind: "BuildConfig" 
apiVersion: "v1"
metadata: 
  name: "spring-client-pipeline" 
  namespace: spring-client-ns-lab2-jenkins
spec: 
  source: 
    git: 
      uri: "https://github.com/IraAngeles-IBM/spring-client" 
      ref: "master" 
  strategy: 
    jenkinsPipelineStrategy: 
      jenkinsfilePath: Jenkinsfile-oc 
      env: 
        - name: "LOGIN_URL" 
          value: "https://c115-e.us-south.containers.cloud.ibm.com" 
        - name: "LOGIN_PORT" 
          value: "30682" 
        - name: "PROJECT" 
          value: "spring-client-ns-lab2-jenkins"
